services:
  app:
    image: "123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp:latest"
    networks:
      - laravel

  nginx:
    image: nginx:stable
    ports:
      - ${FORWARD_NGINX_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html/public
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
